sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: HGmYYsVeO2cD7jkmbux1w5quCXJ6jHV+tjEXp2jNkqoQMAv8jkXAqEzj7eDHs27Nvl27uAtyY0e6WVJrDEdCp5f++58tDHRrcC+3sJtD269jlT0FeXyfIVFHEFdbnd5qWD/CEf8XTxzAMIkFCp/cxwvK+8nUutpB5U4glg8ZHzNqby8/hBseb+DWXpgwgblphb1a0hBUySgtQU/SAnXL33TxIKNWIzkSKxgaLXUbT4WNJP++YGhDCgm2Ck0080/65ZibtNC8ET/atRExA3+8cno489grqBR7OYZiGKmwAXo53hogZoyYISePbOzluy5qG+BUMDJY+LK9a+R+5AOb06Mok6PuM+vDWgsUIiQS4KswJK8S2TFp0cscobNkYrytBBf3i+QdEIVIAQ5lqXHA7ngcw1o92VVOBZZf61synIm9QEyjOO4JbQSh5lbt5Pan3ZHo7KzIWyKag6a/p+9T5VM1vjlEBDLnRMBHnlClMr1kygeAvZunfajyM7S8Hdcy6t7xQ9gMqSBJ0HpB7H+Cwqk6rCpka+e7CJXixPkpgnjL+lLhxKeis7+Jzup0O4ZpGn8nTyovvqUts5VPsx2pJ+bJUmXZL3T+ZM1DRKb9ojSU7qm/vgpZYRSjr6Wd64dpNPAKggZ4+NyZks4VSTAqrP01uYPqKf3RCFMBL/PJBPQ=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Judgment-House_3746
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy